import pdfkit
####################### Authentication ##################
# path to files containing
username =  "/home/mokaguys/Apps/CIP_API/auth_username.txt"
pw = "/home/mokaguys/Apps/CIP_API/auth_pw.txt"

####################### Requests module ##################
#the proxy settings for requests module
proxy={'http':'proxy.gstt.local:80'}

################# report modifications #####################
# New organisation name
org_name="Viapath"
# New line for header
new_header_line="This result sheet has been generated by "+org_name+" using data obtained from the Genomics England APIs."

# Where the patient information template can be found
new_table="/home/mokaguys/Apps/CIP_API/patient_info_table_template.html"

# What colour do you want to change the header banner to?
new_banner_css="#c497c2;\n    height: 100px;"

########################### pdfkit ##########################
# Where do you want the outputs?
html_reports="/home/mokaguys/Documents/GeL_reports/html/"
pdf_dir="/home/mokaguys/Documents/GeL_reports/"

# path to the wkhtmltopdf executable
pdfkitconfig = pdfkit.configuration(wkhtmltopdf="/home/mokaguys/Apps/wkhtmltox/bin/wkhtmltopdf")

